name: GitHub 조직 초대 요청

description: GitHub 조직에 초대를 요청하기 위한 이슈 템플릿입니다.

title: "[GitHub 조직 초대 요청] "

labels:
  - invitation
  - request

body:
  - type: markdown
    attributes:
      value: |
        <br/>
        환영합니다! GitHub 조직에 초대를 요청하기 위해 아래 양식을 작성해주세요.

  - type: dropdown
    id: request-type
    attributes:
      label: 요청 유형
      options:
        - GitHub 조직 초대 요청
    validations:
      required: true

  - type: dropdown
    id: organization
    attributes:
      label: 조직
      options:
        - https://github.com/innodg
    validations:
      required: true

  - type: input
    id: github-profile-link
    attributes:
      label: GitHub 프로필 링크
      placeholder: https://github.com/octocat
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: 이름
      placeholder: 김개발
    validations:
      required: true

  - type: input
    id: school
    attributes:
      label: 학교명
      placeholder: 바이브고등학교 (지원서 작성시 입력한 학교명과 동일하게 작성해주세요)
    validations:
      required: true

  - type: input
    id: student-contact
    attributes:
      label: 학생 연락처
      placeholder: 010-1234-5678 (지원서 작성시 입력한 학생 연락처와 동일하게 작성해주세요. 지원서에 학생 연락처를 기입하지 않은 경우 생략 가능합니다.)
    validations:
      required: false

  - type: input
    id: parent-contact
    attributes:
      label: 학부모 연락처
      placeholder: 010-1234-5678 (지원서 작성시 입력한 학부모 연락처와 동일하게 작성해주세요. 지원서에 학부모 연락처를 기입하지 않은 경우 생략 가능합니다.)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <br/>
        초대 요청을 제출하면 GitHub 계정과 연결된 이메일 주소로 초대장을 발송합니다. 초대장을 수락하면 조직에 참여할 수 있습니다. 감사합니다!
