name: "Workflow: User Invitation GitHub Organization"

on:
  issues:
    types:
      - opened
  workflow_dispatch:
    inputs:
      issue-number:
        description: "Issue number"
        required: true

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  invite_user:
    name: "Invite User to GitHub Organization"

    runs-on: ubuntu-latest

    steps:
      - name: Generate bot token
        id: bot-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          repositories: |
            operations
            preliminary-stages

      # - name: Assign bot to issue
      #   continue-on-error: true
      #   shell: bash
      #   env:
      #     GH_TOKEN: ${{ steps.bot-token.outputs.token }}
      #   run: |
      #     BOT_SLUG=$(gh api /app --jq '.slug')
      #     BOT_LOGIN="${BOT_SLUG}[bot]"
      #     gh issue edit ${{ github.event.issue.number || github.event.inputs.issue-number }} \
      #       --add-assignee "$BOT_LOGIN" \
      #       -R ${{ github.event.repository.full_name }}

      - name: Check event payload - from issue
        if: |
          github.event_name != 'workflow_dispatch'
        shell: pwsh
        run: |
          $eventPayload = '${{ toJson(github) }}'
          $eventPayload | Out-File -FilePath ${{github.workspace}}/payload.json -Force

      - name: Check event payload - from workflow_dispatch
        if: |
          github.event_name == 'workflow_dispatch'
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          $eventPayload = gh api /repos/${{ github.repository }}/issues/${{ github.event.inputs.issue-number }}
          $eventPayload | Out-File -FilePath ${{github.workspace}}/payload.json -Force

      - name: Verify event payload
        shell: pwsh
        run: |
          $payload = Get-Content "${{ github.workspace }}/payload.json"
          $payload

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Checkout quest validator repository
        uses: actions/checkout@v6
        with:
          repository: innodg/operations
          path: operations
          token: ${{ steps.bot-token.outputs.token }}

      # - name: Restore applicant details
      #   shell: pwsh
      #   env:
      #     APPLICANTS: ${{ secrets.APPLICANTS }}
      #   run: |
      #     $env:APPLICANTS | Out-File -FilePath "${{ github.workspace }}/operations/data/applicants.csv" -Encoding utf8

      - name: Validate issue
        shell: bash
        run: |
          pushd ./operations

          dotnet run --project ./src/QuestValidator.IssuePayloadCheck.ConsoleApp -- \
            --input "${{ github.workspace }}/payload.json" \
            --output "${{ github.workspace }}/issue.json" \
            --start-date "${{ vars.START_DATE_INVITATION }}" \
            --due-date "${{ vars.DUE_DATE_INVITATION }}"
          
          popd

      - name: Verify result payload
        shell: pwsh
        run: |
          $result = Get-Content "${{ github.workspace }}/issue.json" | ConvertFrom-Json
          $result

      - name: Check validation result
        id: issue
        shell: pwsh
        run: |
          $result = Get-Content "${{ github.workspace }}/issue.json" | ConvertFrom-Json

          $tzi = [TimeZoneInfo]::FindSystemTimeZoneById("Asia/Seoul")

          # Common
          echo "issueNumber=$($result.number)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
          echo "requestType=$($result.body.requestType)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
          echo "submittedAt=$([TimeZoneInfo]::ConvertTime($result.createdAt, $tzi).ToString("yyyy-MM-dd HH:mm:ss.fff") + " +09:00")" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
          echo "dueBy=$([TimeZoneInfo]::ConvertTime($result.dueDate, $tzi).ToString("yyyy-MM-dd HH:mm:ss.fff") + " +09:00")" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

          # Verification result
          echo "isValid=$($result.isValid)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
          echo "invalidReasons=$('<ul><li> ' + $($result.invalidReasons -join '</li><li> ') + '</li></ul>')" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

          # Invitation details
          echo "githubId=$($result.createdBy)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append
          echo "githubOrg=$($result.body.gitHubOrganisation)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf-8 -Append

      - name: Comment to issue - Acknowledge
        if: |
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ steps.bot-token.outputs.token }}
          issue-number: ${{ steps.issue.outputs.issueNumber }}
          emoji: "+1,rocket"
          body: |
            👋🏼 @${{ steps.issue.outputs.githubId }} 님!

            생성하신 이슈는 현재 확인 중이며, 완료 여부를 확인한 후 다시 알려드리겠습니다.

      - name: Add a label - Invalid
        if: |
          steps.issue.outputs.isValid == 'false' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue edit ${{ steps.issue.outputs.issueNumber }} \
            --add-label "invalid" \
            -R ${{ github.event.repository.full_name }}

      - name: Comment to issue - Invalid
        if: |
          steps.issue.outputs.isValid == 'false' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ steps.bot-token.outputs.token }}
          issue-number: ${{ steps.issue.outputs.issueNumber }}
          body: |
            👋🏼 @${{ steps.issue.outputs.githubId }} 님!

            - 요청 시각: ${{ steps.issue.outputs.submittedAt }}
            - 요청 마감 시각: ${{ steps.issue.outputs.dueBy }}

            하지만 제출하신 요청은 다음과 같은 이유로 인해 유효하지 않습니다. 😢

            ${{ steps.issue.outputs.invalidReasons }}

      - name: Close issue - Invalid
        if: |
          steps.issue.outputs.isValid == 'false' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue close ${{ steps.issue.outputs.issueNumber }} \
            -c "제출한 요청이 유효하지 않습니다. 이슈를 닫습니다." \
            -R ${{ github.event.repository.full_name }}

      - name: Checkout repository
        if: |
          steps.issue.outputs.isValid == 'true' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        uses: actions/checkout@v6

      - name: Invite user to organization
        if: |
          steps.issue.outputs.isValid == 'true' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          ${{ github.workspace }}/scripts/Invite-ToGitHub.ps1 `
            -GitHubOrg "${{ steps.issue.outputs.githubOrg }}" `
            -GitHubId "${{ steps.issue.outputs.githubId }}"

      - name: Add label - Complete
        if: |
          steps.issue.outputs.isValid == 'true' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue edit ${{ steps.issue.outputs.issueNumber }} \
          --add-label "complete" \
          -R ${{ github.event.repository.full_name }}

      - name: Remove label - request
        if: |
          steps.issue.outputs.isValid == 'true' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue edit ${{ steps.issue.outputs.issueNumber }} \
          --remove-label "request" \
          -R ${{ github.event.repository.full_name }}

      - name: Comment to issue - Complete
        if: |
          steps.issue.outputs.isValid == 'true' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ steps.bot-token.outputs.token }}
          issue-number: ${{ steps.issue.outputs.issueNumber }}
          emoji: "+1,rocket"
          body: |
            👋🏼 @${{ steps.issue.outputs.githubId }}님!

            GitHub 계정에 등록한 이메일 주소로 초대장을 발송했습니다. 초대장을 수락하면 조직에 참여할 수 있습니다.
            
            아래는 초대장 이메일의 예시입니다. 메일이 도착하지 않으면 스팸메일함도 확인해 보세요.

            <img src="https://raw.githubusercontent.com/innodg/preliminary-stages/refs/heads/main/images/github-invitation.png" alt="GitHub 초대장 이메일 예시" width="640" />

            감사합니다!

      - name: Close issue - Complete
        if: |
          steps.issue.outputs.isValid == 'true' &&
          steps.issue.outputs.requestType == 'GitHub 조직 초대 요청'
        shell: bash
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh issue close ${{ steps.issue.outputs.issueNumber }} \
            -c "초대 요청을 완료했습니다. 이슈를 닫습니다." \
            -R ${{ github.event.repository.full_name }}
